export default {
  showFooter: false,
  isSidebarCompact: false,
  showBreadcrumb: false,
  menuAutoCollapsed: true,
  mode: 'light',
  layout: 'side',
  splitMenu: false,
  sideMode: 'light',
  isFooterAside: false,
  isSidebarFixed: true,
  isHeaderFixed: true,
  isUseTabsRouter: false,
  showHeader: true,
  brandTheme: '#EBB105',
};
